#!/bin/bash

export LAB=TOUPPER

(make clean; make) || exit 1

total=0
totalmax=0

rm -f total.txt *out total.txt
touch none

# Test driver
function runtest {
  prog=$1
  args=$2
  testinput=$3
  compout=$4
  grade=$5
  totalmax=`expr $totalmax + $grade`;
  inputdescr=
  if [ "$testinput" != "none" ]; then
      inputdescr=" < $testinput"
  fi
  descr="$prog $args $inputdescr"
  
  echo "======= $descr ==========="

  #Run tested program
  if [ $compout -eq 0 ]; then
  	./$prog $args < $testinput > $prog.out
  	if [ $? -eq 0 ]; then
      		cat $prog.out
      		echo Test passed...;
      		printf "%-36s: %-3d of %-3d\n" "$descr " $grade $grade >> total.txt
      		total=`expr $total + $grade`;
          echo PASS $args >> inputs.out;
  	else
      		cat $prog.out
      		echo "*****Test Failed*****";
      		printf "%-36s: %-3d of %-3d\n" "$descr " 0 $grade >> total.txt
          echo FAIL $args >> inputs.out;
  	fi
  else 
  	echo $args | ./$prog > $prog.out
  	echo $args | ./$prog.org > $prog.org.out
  	diff $prog.out $prog.org.out > diff.out
  	if [ $? -eq 0 ]; then
      		cat $prog.out
      		echo Test passed...;
      		printf "%-36s: %-3d of %-3d\n" "$descr " $grade $grade >> total.txt
      		total=`expr $total + $grade`;
          echo PASS $args >> inputs.out;
  	else
      		echo "*****Test Failed*****";
      		echo ------ Your Output ----------
      		cat $prog.out
      		echo ------ Expected Output ------
      		cat $prog.org.out
      		echo ------ Difference -----------
      		cat diff.out
      		echo -----------------------------
      		printf "%-36s: %-3d of %-3d\n" "$descr " 0 $grade >> total.txt
          echo FAIL $args >> inputs.out;
  	fi
  fi
  echo
}

# List of tests running
runtest toupper abcde none 1 2
runtest toupper abc109 none 1 2 

echo
echo
echo   "-------------------------------------------------"
echo   "CS240: $LAB. $USER   "
echo   "-------------------------------------------------"
cat total.txt
echo   "-------------------------------------------------"
echo   "CS240: $LAB. $USER" `date` " Total: " $total of $totalmax >> total.out
echo >> total.out

cat total.out
cat total.out >> .local.total.out

#Do not remove or comment these lines. They are used for monitoring progress.
# labout=/homes/cs240/LABOUT/$LAB/$USER/total.txt
# cat total.out >> $labout
# git add *.h *.c total.out >> .local.git.out
# git commit -a -m "$total of $totalmax" >> .local.git.out

echo "Generating feedback"
spinner suggest


